language: python
python:
  - "3.6"
install:
  - python setup.py install -q
  - pip install coverage
  - pip install coveralls
script:
  - pylint --load-plugins pylint_django officemanager/*/**.py
  - python officemanager/manage.py runserver
  - coverage run --source=department officemanager/manage.py test department
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - dzdimati@gmail.com
    on_succes: change
