language: python
python:
  - "3.6"
services:
  # - mysql
before_script:
  # - mysql -e 'CREATE DATABASE travisdb;'
install:
  - python setup.py -q install
script:
  - python officemanager/manage.py test
# this command exited with error. No file to run: 'test'
#  - coverage run --source=officemanager/manage.py test
after_success:
  - coveralls