language: python
python:
  - "3.6"
services:
  # - mysql
before_script:
  # - mysql -e 'CREATE DATABASE travisdb;'
install:
  - python setup.py install -q
script:  
  - python officemanager/manage.py makemigrations
  - python officemanager/manage.py migrate

#- pylint --load-plugins pylint_django officemanager/department/*

# this command exited with error. No file to run: 'test'
#  - coverage run --source=officemanager/manage.py test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - dzdimati@gmail.com
    on_succes: change