# Generated by Django 2.2.4 on 2019-09-03 21:24

from django.db import migrations
from department.models.models import Departments

def add_titles_dep(apps, schema_editor):
    title_list = [
        'Business Intelligence',
        'IT Management',
        'Administration',
        'IT Procurement',
        'IT Security',
        'Network Adminstration',
        'Systems Analyst & Architecture',
        'User Support & Services'
    ]

    for line in title_list:
        dep = Departments(name = line)
        dep.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_titles_dep)
    ]
