# Generated by Django 2.2.4 on 2019-09-04 10:39

from django.db import migrations

TITLE_LIST = [
    'Business Intelligence',
    'IT Management',
    'Administration',
    'IT Procurement',
    'IT Security',
    'Network Adminstration',
    'Systems Analyst & Architecture',
    'User Support & Services'
    ]

def add_titles_dep(apps, schema_editor):
    Dep = apps.get_model('department', 'Departments')
    Dep.objects.bulk_create((Dep(name=i) for i in TITLE_LIST))

def reverce_add(apps, schema_editor):
    Dep = apps.get_model('department', 'Departments')
    Dep.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_titles_dep, reverce_add),
    ]
